{
 "title": "mydashboard2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rate of Inbound and outbound request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_outbound_9080__productpage_default_svc_cluster_local_upstream_rq_total[20s])",
     "legendFormat": "Product Page(outbound)"
    },
    {
     "expr": "rate(envoy_cluster_inbound_9080__reviews_default_svc_cluster_local_upstream_rq_total[20s])",
     "legendFormat": "Reviews(Inbound)"
    },
    {
     "expr": "rate(envoy_cluster_inbound_9080__details_default_svc_cluster_local_upstream_rq_total[20s])",
     "legendFormat": "Details(Inbound)"
    },
    {
     "expr": "rate(envoy_cluster_inbound_9080__ratings_default_svc_cluster_local_upstream_rq_total[20s])",
     "legendFormat": "Rating(Inbound)"
    },
    {
     "expr": "rate(envoy_cluster_outbound_9080__reviews_default_svc_cluster_local_upstream_rq_total[20s])",
     "legendFormat": "Reviews(Outbound)"
    }
   ]
  },
  {
   "title": "Inbound Outbound Total Request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(envoy_cluster_outbound_9080__productpage_default_svc_cluster_local_upstream_rq_total)"
    },
    {
     "expr": "envoy_cluster_inbound_9080__details_default_svc_cluster_local_upstream_rq_total"
    },
    {
     "expr": "envoy_cluster_inbound_9080__reviews_default_svc_cluster_local_upstream_rq_total"
    },
    {
     "expr": "envoy_cluster_inbound_9080__ratings_default_svc_cluster_local_upstream_rq_total"
    },
    {
     "expr": "envoy_cluster_outbound_9080__reviews_default_svc_cluster_local_upstream_rq_total"
    }
   ]
  },
  {
   "title": "Istio-Request-count-rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(istio_request_count[30s])",
     "legendFormat": "{{source_service}},{{destination_service}}"
    }
   ]
  },
  {
   "title": "Istio-Request-count-total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "istio_request_count{source_service!=\"unknown\"}",
     "legendFormat": "{{source_service}},{{destination_service}}"
    }
   ]
  },
  {
   "title": "HTTP Request_duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (http_request_duration_microseconds{quantile=\"0.9\", job!~\"kubernetes-service-endpoints\"} ) by (job ) / 1000",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "http_request_duration_microseconds{quantile=\"0.9\" , handler=\"query_range\" , job=\"kubernetes-service-endpoints\" } / 1000 ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Container memory cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_cache{namespace=\"default\"}[10m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Container CPU usages sec rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Http request per running container at nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_total{beta_kubernetes_io_instance_type=\"t2.small\", kops_k8s_io_instancegroup=\"master-us-east-2a\"}) /  sum(kubelet_running_container_count{beta_kubernetes_io_instance_type=\"t2.small\",kops_k8s_io_instancegroup=\"master-us-east-2a\"})",
     "legendFormat": "Master"
    },
    {
     "expr": "sum(http_requests_total{beta_kubernetes_io_instance_type=\"t2.small\", kops_k8s_io_instancegroup=\"nodes\"}) /  sum(kubelet_running_container_count{beta_kubernetes_io_instance_type=\"t2.small\",kops_k8s_io_instancegroup=\"nodes\"})",
     "legendFormat": "Node"
    }
   ]
  },
  {
   "title": "Total http request per sec grouped by job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Http Request Size(bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_size_bytes{quantile=\"0.99\"}) by (job)",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  },
  {
   "title": "Worker node running containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 71 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count{beta_kubernetes_io_instance_type=\"t2.small\",kubernetes_io_role=\"node\"})"
    }
   ]
  },
  {
   "title": "Master node running containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 71 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kubelet_running_container_count{beta_kubernetes_io_instance_type=\"t2.small\",kubernetes_io_role=\"master\"}"
    }
   ]
  }
 ]
}